Repository mlcraft-io/mlcraft, pull requests merged in 2023-05, with the labels that each got.

#64 feat(datasources): Dremio datasource
  docs/datasources/dremio/README.md
  docs/examples/dremio/docker-compose.yml
  docs/examples/dremio/run_dremio.sh
  services/client/src/assets/images/dremio.svg
  services/client/src/components/DataSourceForm.js
  services/client/src/pages/DataSchemas.js
  services/cubejs/package.json
  services/cubejs/src/routes/index.js
  services/cubejs/yarn.lock
Labels: documentation, enhancement

#65 feat(datasources): Elasticsearch datasource
  docs/datasources/elasticsearch/README.md
  docs/examples/elasticsearch/docker-compose.yml
  docs/examples/elasticsearch/run_elasticsearch.sh
  docs/images/elasticsearch1.png
  docs/images/elasticsearch2.png
  services/client/src/assets/images/elasticsearch.svg
  services/client/src/components/DataSourceForm.js
  services/cubejs/index.js
  services/cubejs/package.json
  services/cubejs/src/routes/index.js
  services/cubejs/yarn.lock
Labels: documentation, enhancement

#67 feat(datasources): KSQL datasource
  docs/datasources/ksql/README.md
  docs/examples/ksql/docker-compose.yml
  docs/examples/ksql/run_ksql.sh
  services/client/src/assets/images/ksql.svg
  services/client/src/components/DataSourceForm.js
  services/cubejs/index.js
  services/cubejs/package.json
  services/cubejs/src/routes/index.js
  services/cubejs/yarn.lock
Labels: documentation, enhancement

#66 feat(datasources): Databricks datasource
  docs/datasources/databricks/README.md
  services/client/src/assets/images/databricks.svg
  services/client/src/components/DataSourceForm.js
  services/cubejs/Dockerfile
  services/cubejs/index.js
  services/cubejs/package.json
  services/cubejs/yarn.lock
Labels: enhancement

#68 feat(datasources): Firebolt datasource
  docs/datasources/firebolt/README.md
  services/client/src/assets/images/firebolt.svg
  services/client/src/components/DataSourceForm.js
  services/cubejs/index.js
  services/cubejs/package.json
  services/cubejs/yarn.lock
Labels: documentation, enhancement

#61 fix(explorations): granularities
  services/actions/src/rpc/checkAlert.js
  services/actions/src/rpc/checkReport.js
  services/actions/src/rpc/sendExplorationScreenshot.js
  services/client/src/components/AlertForm.js
  services/client/src/components/AlertModal.js
  services/client/src/components/ExploreCubes.js
  services/client/src/components/ExploreCubes.module.css
  services/client/src/components/ExploreCubesCategoryItem.js
  services/client/src/components/ExploreCubesCategoryItem.module.css
  services/client/src/components/ExploreCubesCategoryItemFilter.js
  services/client/src/components/ExploreCubesCategoryItemFilter.module.css
  services/client/src/components/ExploreCubesSection.js
  services/client/src/components/ExploreCubesSubSection.js
  services/client/src/components/ExploreCubesSubSection.module.css
  services/client/src/components/ReportForm.js
  services/client/src/components/ReportModal.js
  services/client/src/components/TableView.js
  services/client/src/hooks/useAlertsConfig.js
  services/client/src/hooks/useAnalyticsQuery.js
  services/client/src/hooks/useAnalyticsQueryMembers.js
  services/client/src/hooks/useDataSourceMeta.js
  services/client/src/hooks/usePlayground.js
Labels: bug

#63 feat(docs): detailed, shareable and downloadable docs
  services/actions/src/rpc/fetchMeta.js
  services/actions/src/rpc/genSchemasDocs.js
  services/actions/src/utils/markdownHelpers.js
  services/client/src/Routes.js
  services/client/src/components/DocsSection.js
  services/client/src/components/DocsSection.module.css
  services/client/src/components/MarkdownViewer.js
  services/client/src/components/SelectBranch.js
  services/client/src/pages/DataSchemas.js
  services/client/src/pages/Docs.js
  services/client/src/utils/downloadBlob.js
Labels: enhancement
